import { ElementsModel, ItemsRentabilidadContableModel, RentabilidadContableModel } from 'src/app/shared/models/rentabilidad-contable/renta-contable.model';
import { Injectable } from '@angular/core';
import { ReturnStatement } from '@angular/compiler';

@Injectable({
  providedIn: 'root'
})
export class RentContService {

  itemsRentabilidadContable: ItemsRentabilidadContableModel[] = [];

  constructor() { }

  getRentContItems(): ItemsRentabilidadContableModel[] {

    this.itemsRentabilidadContable = [];

    this.itemsRentabilidadContable.push(
      {
        idTipo: 1,
        tipo: 'LIQUIDACION',
        tracto: 'TT1280',
        liquidacion: 33027,
        viajes: 1,
        diasViaje: 6,
        kmCargados: 2789,
        kmVacios: 13,
        ltsDiesel: 1695,
        rendimiento: 1.66,
        ingresoTotal: 57150,
        combustible: 29195,
        porCombustible: '51%',
        casetas: 8362,
        porCasetas: '15%',
        sueldosLiquidacion: 7555,
        porSueldosLiquidacion: '13%',
        otros: 9837,
        porOtros: '17%',
        costoDirecto: 54949,
        porCostoDirecto: '96%',
        sueldoBase: 450,
        porSueldoBase: '1%',
        cargaSocialNomina: 3602,
        porCargaSocialNomina: '6%',
        fijoMantenimiento: 2528,
        porFijoMantenimiento: '4%',
        variableMantenimiento: 2684,
        porVariableMantenimiento: '5%',
        fijoTransportacion: 5483,
        porFijoTransportacion: '10%',
        otrasVariablesTransportacion: 1793,
        porOtrasVarialblesTransportacion: '3%',
        totalCostosAdicionales: 16542,
        porTotalCostosAdicionales: '29%',
        margenUtilidadBruta: 14341,
        porMargenUtilidadBruta: '-25%'
      },
      {
        idTipo: 2,
        tipo: 'CAJA SECA',
        tracto: 'TT1256',
        liquidacion: 33027,
        viajes: 1,
        diasViaje: 6,
        kmCargados: 2789,
        kmVacios: 13,
        ltsDiesel: 1695,
        rendimiento: 1.66,
        ingresoTotal: 57150,
        combustible: 29195,
        porCombustible: '51%',
        casetas: 8362,
        porCasetas: '15%',
        sueldosLiquidacion: 7555,
        porSueldosLiquidacion: '13%',
        otros: 9837,
        porOtros: '17%',
        costoDirecto: 54949,
        porCostoDirecto: '96%',
        sueldoBase: 450,
        porSueldoBase: '1%',
        cargaSocialNomina: 3602,
        porCargaSocialNomina: '6%',
        fijoMantenimiento: 2528,
        porFijoMantenimiento: '4%',
        variableMantenimiento: 2684,
        porVariableMantenimiento: '5%',
        fijoTransportacion: 5483,
        porFijoTransportacion: '10%',
        otrasVariablesTransportacion: 1793,
        porOtrasVarialblesTransportacion: '3%',
        totalCostosAdicionales: 16542,
        porTotalCostosAdicionales: '29%',
        margenUtilidadBruta: 14341,
        porMargenUtilidadBruta: '-25%'
      },
      {
        idTipo: 2,
        tipo: 'CAJA SECA',
        tracto: 'TT1277',
        liquidacion: 33027,
        viajes: 1,
        diasViaje: 6,
        kmCargados: 2789,
        kmVacios: 13,
        ltsDiesel: 1695,
        rendimiento: 1.66,
        ingresoTotal: 57150,
        combustible: 29195,
        porCombustible: '51%',
        casetas: 8362,
        porCasetas: '15%',
        sueldosLiquidacion: 7555,
        porSueldosLiquidacion: '13%',
        otros: 9837,
        porOtros: '17%',
        costoDirecto: 54949,
        porCostoDirecto: '96%',
        sueldoBase: 450,
        porSueldoBase: '1%',
        cargaSocialNomina: 3602,
        porCargaSocialNomina: '6%',
        fijoMantenimiento: 2528,
        porFijoMantenimiento: '4%',
        variableMantenimiento: 2684,
        porVariableMantenimiento: '5%',
        fijoTransportacion: 5483,
        porFijoTransportacion: '10%',
        otrasVariablesTransportacion: 1793,
        porOtrasVarialblesTransportacion: '3%',
        totalCostosAdicionales: 16542,
        porTotalCostosAdicionales: '29%',
        margenUtilidadBruta: 14341,
        porMargenUtilidadBruta: '-25%'
      },
      {
        idTipo: 2,
        tipo: 'LIQUIDACION',
        tracto: 'TT1288',
        liquidacion: 33027,
        viajes: 1,
        diasViaje: 6,
        kmCargados: 2789,
        kmVacios: 13,
        ltsDiesel: 1695,
        rendimiento: 1.66,
        ingresoTotal: 57150,
        combustible: 29195,
        porCombustible: '51%',
        casetas: 8362,
        porCasetas: '15%',
        sueldosLiquidacion: 7555,
        porSueldosLiquidacion: '13%',
        otros: 9837,
        porOtros: '17%',
        costoDirecto: 54949,
        porCostoDirecto: '96%',
        sueldoBase: 450,
        porSueldoBase: '1%',
        cargaSocialNomina: 3602,
        porCargaSocialNomina: '6%',
        fijoMantenimiento: 2528,
        porFijoMantenimiento: '4%',
        variableMantenimiento: 2684,
        porVariableMantenimiento: '5%',
        fijoTransportacion: 5483,
        porFijoTransportacion: '10%',
        otrasVariablesTransportacion: 1793,
        porOtrasVarialblesTransportacion: '3%',
        totalCostosAdicionales: 16542,
        porTotalCostosAdicionales: '29%',
        margenUtilidadBruta: 14341,
        porMargenUtilidadBruta: '-25%'
      },
    );

    return this.itemsRentabilidadContable;

  }


}
