export interface CotizacionModel{
  idCotizacion?: number,
  folio?: number,
  sencillo?: boolean,
  tipoViaje?: string,
  regresa_vacio?: boolean,
  regreso?: string,
  id_ingreso?: string,
  id_area: number,
  unidadNegocio?: string,
  id_tipo_operacion: number,
  tipoOperacion?: string,
  clasificacion?:string,
  cliente: string,
  origen: string,
  destino: string,
  kms_ida: number,
  kms_regreso?: number,
  kms_totales?: number,
  casetas: number,
  casetas_si: number,
  casetas_regreso?: number,
  casetas_regreso_si?: number,
  casetas_total_sin_impuestos?: number,
  diesel: number,
  diesel_sin_impuestos: number,
  diesel_total_sin_impuestos: number,
  num_estancias_ida: number,
  num_maniobras_ida: number,
  ton_carga_ida: number,
  num_estancias_regreso: number,
  num_maniobras_regreso: number,
  ton_carga_regreso: number,
  clienta_paga: boolean,
  clientePagaCasetas: string,
  tarifaFinal: number,
  costoViaje: number,
  toneladas: number,
  costo_tonelada: number,
  costoPorKm: number,
  ingresoPorKm: number,
  tarifa25?: number,
  tarifa30?: number,
  tarifa35?: number,
  tarifa40?: number,
  porcentajeFinal?: number,
  status?: string,
  rend_cargado?: number,
  rend_vacio?: number,
  variables?: VariablesCotizacionModel[],
  costos_ida?: DetalleCotizacionModel[],
  costos_regreso?: DetalleCotizacionModel[]
}
export interface VariablesCotizacionModel{
  variable: string,
  valor?: number
}

export interface DetalleCotizacionModel{
  descripcion: string,
  unidad_medida:string,
  costo?: string,
  subtotal?: string,
  porcentaje?:number
}

export interface NuevaCotizacionModel{
  idCotizacion?:number,
  sencillo: boolean,
  regresa_vacio: boolean,
  id_ingreso: string,
  id_area: number,
  id_tipo_operacion: number,
  clasificacion: string,
  cliente: string,
  origen: string,
  destino: string,
  kms_ida: number,
  kms_regreso: number,
  casetas: number,
  casetas_si: number,
  casetas_regreso: number,
  casetas_regreso_si: number,
  diesel: number,
  costo: number,
  num_estancias_ida: number,
  num_maniobras_ida: number,
  ton_carga_ida: number,
  num_estancias_regreso: number,
  num_maniobras_regreso: number,
  ton_carga_regreso:number,
  cliente_paga: boolean,
  tarifaFinal: number,
  costoViaje: number,
  tipoViaje?: string,
  regreso?: string,
  clientePagaCasetas?: string,
  unidadNegocio?: string,
  tipoOperacion?: string,
  toneladas?: number,
  costo_tonelada?: number,
  rend_cargado?: number,
  rend_vacio?: number,
  variables?: VariablesCotizacionModel[],
  costos_ida?: DetalleCotizacionModel[],
  costos_regreso?: DetalleCotizacionModel[]
  
}
