export enum API_URLS{
    LOGEO = 'api/Login',
    GET_INGRESOS_ANUALES = 'api/Ingresos/IngresosAnuales',
    GET_INGRESOS_ANUALES_2024 = 'api/Ingresos/IngresosAnuales2024',
    GET_INGRESOS_ANUALES_2025 = 'api/Ingresos/IngresosAnuales2025',
    GET_INGRESOS_ANUALES_2026 = 'api/Ingresos/IngresosAnuales2026',
    /*==================================2023===============================================================*/
    GET_INGRESOS_ANUALES_DETALLADO_enero = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202301/01',
    GET_INGRESOS_ANUALES_DETALLADO_febrero = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202302/02',
    GET_INGRESOS_ANUALES_DETALLADO_marzo = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202303/03',
    GET_INGRESOS_ANUALES_DETALLADO_abril = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202304/04',
    GET_INGRESOS_ANUALES_DETALLADO_mayo = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202305/05',
    GET_INGRESOS_ANUALES_DETALLADO_junio = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202306/06',
    GET_INGRESOS_ANUALES_DETALLADO_julio = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202307/07',
    GET_INGRESOS_ANUALES_DETALLADO_agosto = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202308/08',
    GET_INGRESOS_ANUALES_DETALLADO_septiembre = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202309/09',
    GET_INGRESOS_ANUALES_DETALLADO_octubre = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202310/10',
    GET_INGRESOS_ANUALES_DETALLADO_noviembre = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202311/11',
    GET_INGRESOS_ANUALES_DETALLADO_diciembre = 'api/Ingresos/IngresosAnualesDetalladoMensual/2023/202312/12',
    /*==================================2024===============================================================*/
    GET_INGRESOS_ANUALES_DETALLADO_enero2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202401/01',
    GET_INGRESOS_ANUALES_DETALLADO_febrero2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202402/02',
    GET_INGRESOS_ANUALES_DETALLADO_marzo2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202403/03',
    GET_INGRESOS_ANUALES_DETALLADO_abril2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202404/04',
    GET_INGRESOS_ANUALES_DETALLADO_mayo2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202405/05',
    GET_INGRESOS_ANUALES_DETALLADO_junio2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202406/06',
    GET_INGRESOS_ANUALES_DETALLADO_julio2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202407/07',
    GET_INGRESOS_ANUALES_DETALLADO_agosto2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual/2024/202408/08',
    GET_INGRESOS_ANUALES_DETALLADO_septiembre2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2024/202409/09',
    GET_INGRESOS_ANUALES_DETALLADO_octubre2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2024/202410/10',
    GET_INGRESOS_ANUALES_DETALLADO_noviembre2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2024/202411/11',
    GET_INGRESOS_ANUALES_DETALLADO_diciembre2024 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2024/202412/12',
        /*==================================2025===============================================================*/
    GET_INGRESOS_ANUALES_DETALLADO_enero2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202501/01',
    GET_INGRESOS_ANUALES_DETALLADO_febrero2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202502/02',
    GET_INGRESOS_ANUALES_DETALLADO_marzo2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202503/03',
    GET_INGRESOS_ANUALES_DETALLADO_abril2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202504/04',
    GET_INGRESOS_ANUALES_DETALLADO_mayo2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202505/05',
    GET_INGRESOS_ANUALES_DETALLADO_junio2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202506/06',
    GET_INGRESOS_ANUALES_DETALLADO_julio2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202507/07',
    GET_INGRESOS_ANUALES_DETALLADO_agosto2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202508/08',
    GET_INGRESOS_ANUALES_DETALLADO_septiembre2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202509/09',
    GET_INGRESOS_ANUALES_DETALLADO_octubre2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202510/10',
    GET_INGRESOS_ANUALES_DETALLADO_noviembre2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202511/11',
    GET_INGRESOS_ANUALES_DETALLADO_diciembre2025 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2025/202512/12',
    /*==================================2026===============================================================*/
    GET_INGRESOS_ANUALES_DETALLADO_enero2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202601/01',
    GET_INGRESOS_ANUALES_DETALLADO_febrero2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202602/02',
    GET_INGRESOS_ANUALES_DETALLADO_marzo2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202603/03',
    GET_INGRESOS_ANUALES_DETALLADO_abril2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202604/04',
    GET_INGRESOS_ANUALES_DETALLADO_mayo2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202605/05',
    // GET_INGRESOS_ANUALES_DETALLADO_junio2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202606/06',
    // GET_INGRESOS_ANUALES_DETALLADO_julio2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202607/07',
    // GET_INGRESOS_ANUALES_DETALLADO_agosto2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202608/08',
    // GET_INGRESOS_ANUALES_DETALLADO_septiembre2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202609/09',
    // GET_INGRESOS_ANUALES_DETALLADO_octubre2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202610/10',
    // GET_INGRESOS_ANUALES_DETALLADO_noviembre2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202611/11',
    // GET_INGRESOS_ANUALES_DETALLADO_diciembre2026 = 'api/Ingresos/IngresosAnualesDetalladoMensual202409/2026/202612/12',

    GET_INGRESOS_ANUALES_CHART = 'api/Ingresos/IngresosAnualesChart',

    GET_TONELADAS_ANUALES = 'api/Ingresos/ToneladasAnuales',
    GET_TONELADAS_ANUALES_CHART = 'api/Ingresos/ToneladasAnualesChart',

    GET_VIAJES_ANUALES = 'api/Ingresos/ViajesAnuales',
    GET_VIAJES_ANUALES_CHART = 'api/Ingresos/ViajesAnualesChart',

    GET_KMS_ANUALES = 'api/Ingresos/KmsAnuales',
    GET_KMS_ANUALES_CHART = 'api/Ingresos/KmsAnualesChart',

    GET_Rentabilidad_Contable = 'api/Rentabilidad/RentbilidadContable',

    GET_UNIDADES_NEOGCIO = 'api/General/UnidadesNegocio',
    POST_RENTABILIDAD_CONTABLE = 'api/Rentabilidad/RentbilidadContable',
    POST_TRACTOS = 'api/Rentabilidad/RCTractos',
    POST_TRACTOS_BV = 'api/Disponibilidad/PostBitTracto/',
    

    GET_TIPOS_OPERACION = 'api/General/TiposOperacion',
    GET_TIPOS_OPERACION_UDN = 'api/Cotizador/GetOperaciones/',
    POST_CLIENTES_RUTAS = 'api/Rentabilidad/RGClientesRutas',
    POST_RENTABILIDAD_RUTA = 'api/Rentabilidad/RentabilidadRuta',

    POST_COTIZADOR_OBTENER_VARIABLES = 'api/Cotizador/ObtenerVariables',
    POST_COTIZADOR_NUEVA_COTIZACION = 'api/Cotizador/NvaCotizacion',
    GET_COTIZADOR_OBTENER_PRECOTIZACIONES = 'api/Cotizador/GetCotizacionesActivas/PRECOTIZACION',
    GET_COTIZADOR_OBTENER_APROBADAS = 'api/Cotizador/GetCotizacionesActivas/APROBADA',
    GET_COTIZADOR_OBTENER_COTIZACION = 'api/Cotizador/GetCotizacion/',
    POST_COTIZADOR_EDITAR_COTIZACION = 'api/Cotizador/ModCotizacion',
    POST_COTIZADOR_ELIMINAR_COTIZACION = 'api/Cotizador/EliminarCotizacion',
    POST_COTIZADOR_APROBAR_COTIZACION = 'api/Cotizador/AprobarCotizacion',
    GET_COTIZADOR_RENTABILIDAD = 'api/Cotizador/ObtenerRendimientos/',

    GET_KMS_ACTUALES = 'api/Kilometros/KmsMensuales',
    GET_KMS_ACTUALES_MANT = 'api/Kilometros/KmsMensualesAnt',

    GET_COSTOS_MES = 'api/Costos/GetCostosMensuales/',

    POST_RESULT_COSTO_ANUAL = 'api/Costos/GetEdoResultados',
    POST_DETALLE_CUENTA = 'api/Costos/GetDetalleCuenta',
    POST_BALANZA = 'api/costos/PostBalanza',
    POST_COSTOS_UDN = 'api/Costos/PostUdns',
    POST_CENTRO_COSTOS = 'api/Costos/GetCC',
    POST_CA_TPS = 'api/Costos/GetTPSUdN',
    POST_DETALLE_TPS = 'api/Costos/GetAuxiliarRenglon',
    POST_CA_COSTOS = 'api/Costos/GetCtasUdN',
    POST_CA_AUXILIAR = 'api/Costos/GetAuxiliar',
    POST_PROYECCION_COSTOS = 'api/Costos/GetProyeccion',
    POST_CARTERA_CLIENTE = 'api/CarteraClientes/ResumenCarteraClientes',
    POST_RENTABILIDAD_VIAJES = 'api/Rentabilidad/RCViajes',
    POST_CIERRE_CARTERA = 'api/CarteraClientes/CierreCartera',
    POST_ACTUALIZACION_CARTERA = 'api/CarteraClientes/ResumenCarteraClientes',
    POST_CARTERA_TERCEROS = 'api/CarteraClientes/CarteraTerceros',
    POST_ASIGNAR_CLIENTE = 'api/CarteraClientes/AsignarCliente',
    POST_MACROCICLO = 'api/Rentabilidad/MacroCiclo',
    POST_MACROCICLO_DETALLE = 'api/Rentabilidad/MacroCicloDet',
    POST_CLIENTE_RUTA_ORIGEN = 'api/Rentabilidad/ClienteRutaOrigen',
    POST_RUTA_DESTINO = 'api/Rentabilidad/RutaDestino',
    POST_RUTAS = 'api/Rentabilidad/IngrXKmViaje',
    POST_DISPONIBILIDAD_ANUAL = 'api/Disponibilidad/Disponibilidad',
    POST_STATUS_MANUAL = 'api/Disponibilidad/PostCambiarStatus',
    POST_TIPO_OPERACION_OPERADOR = 'api/Disponibilidad/PostCambiarOperacion',
    POST_NUEVO_PRESUPUESTO = 'api/Disponibilidad/PostNuevoPresupuesto',
    POST_EDITAR_PRESUPUESTO = 'api/Disponibilidad/PostModPresupuesto',
    POST_ELIMINAR_PRESUPUESTO = 'api/Disponibilidad/PostEliminarPresupuesto',
    POST_DISPONIBILIDAD_MENSUAL = 'api/Disponibilidad/PostDisponibilidadMensual',
    POST_SUELDO_OPERADOR = 'api/Rentabilidad/SueldoOperador',
    POST_SUELDO_OPERADOR25 = 'api/Rentabilidad/SueldoOperador25',
    POST_SUELDO_OPERADOR26 = 'api/Rentabilidad/SueldoOperador26',
    POST_SUELDO_OPERADOR_ACUMULADO = 'api/Rentabilidad/SueldoAcumulado/',
    POST_SUELDO_DETALLE = 'api/Rentabilidad/SueldoDetalle/',
    POST_SUELDO_DETALLE25 = 'api/Rentabilidad/SueldoDetalle/',
    POST_SUELDO_DETALLE26 = 'api/Rentabilidad/SueldoDetalle/',
    POST_BITACORA_VIAJE = 'api/Disponibilidad/PostBitacoraViaje',
    POST_ACTUALIZAR_MACROCICLO = 'api/Rentabilidad/ActualizaMacroCiclo',
    POST_OPERADOR = 'api/Disponibilidad/GetOperadoresNOM',
    POST_OBSERVACIONES = 'api/Pagos/GuardarObservacionesOperador',
    POST_GUARDAR_PERMISOS = 'api/General/PostGuardarOpcion',
    POST_TRACTO = 'api/Disponibilidad/PostDisponibilidadMensualTracto',
    POST_GUARDAR_BITACORA = 'api/General/PostGuardarBitacora',
    GET_TPS = 'api/Costos/GetTPS/',
    GET_TIPO_USUARIOS = 'api/Login/TiposUsuarios',
    GET_COSTOS_CC = 'api/Costos/GetCC',
    GET_COSTOS_COMPANIAS = 'api/Costos/GetCompanias',
    GET_COSTOS_TIPOS = 'api/Costos/GetTipos',
    GET_COSTOS_CLASES = 'api/Costos/GetClases',
    GET_SCORE_CARD = 'api/Kilometros/ScoreCard',
    GET_SCORE_CARD_2024 = 'api/Kilometros/ScoreCard2024',
    GET_SCORE_CARD_2025 = 'api/Kilometros/ScoreCard2025',
    GET_SCORE_CARD_2026 = 'api/Kilometros/ScoreCard2026',
    GET_INGRESO_OPERADOR = 'api/Kilometros/ViajeOperador/',
    GET_CARTERA_DETALLE = 'api/CarteraClientes/CarteraClientes',
    GET_KMS_MENSUALES = 'api/Kilometros/KmsMensuales/',
    GET_PERIODO_ACTUAL = 'api/CarteraClientes/Periodo',
    GET_CARTERA_CLIENTES = 'api/CarteraClientes/Clientes',
    GET_INDICADORES_CHART = 'api/Kilometros/Indicadores',
    GET_INDICADORES_CHART24 = 'api/Kilometros/Indicadores2024',
    GET_INDICADORES_CHART25 = 'api/Kilometros/Indicadores2025',
    GET_INDICADORES_CHART26 = 'api/Kilometros/Indicadores2026',
    GET_DISPONIBILIDAD_PRESUPUESTO = 'api/Disponibilidad/GetCatPresupuesto/',
    GET_DISPONIBILIDAD_OPERADOR = 'api/Disponibilidad/ObtenerOperador/',
    GET_DISPONIBILIDAD_TRACTO = 'api/Disponibilidad/ObtenerTracto/',
    GET_INGRESOS_X_CLIENTE = 'api/Kilometros/IngresoXCliente/',
    GET_INGRESOS_X_CLIENTE_ANUAL = 'api/Kilometros/IngresoXClienteAnual/',
    GET_METRICA_COBRNZA = 'api/CarteraClientes/MetricaCobranza',
    GET_MACRO_CICLO_CAJA_SECA = 'api/Rentabilidad/GetMacroCicloCajaSeca',
    GET_PAGOS = 'api/Pagos/GetPagosMes/',
    GET_ALTAS_BAJAS = 'api/Disponibilidad/GetAltasBajas/',
    GET_ANTICIPOS ='api/Pagos/GetAnticipos/',
    GET_LIQUIDACION_MENSUALES = 'api/Pagos/GetLiquidacionesMensuales/',
    GET_OBSERVACIONES = 'api/Pagos/GetObservacionesOperador/',
    GET_USUARIOS_ACTIVOS = 'api/General/GetUsuariosActivos',
    GET_USUARIOS_PERMISOS = 'api/General/GetUsuarioPermiso/',
    GET_DETALLES_OPERADOR = 'api/Pagos/GetDetallesOperador/',
    GET_MOTIVOS_BAJAS = 'api/Pagos/GetMotivosBajas/',
    GET_ULTIMO_STATUS ='api/Disponibilidad/GetStUltViaje/',
    GET_DETALLE_VIAJE = 'api/Disponibilidad/GetUltStBitPorViaje/',
    GET_DATOS_OPERADOR = 'api/Disponibilidad/GetOperadores/',
    GET_ULTIMA_POSICION = 'api/Disponibilidad/GetUltimaPosicion/',
    GET_PDF = 'api/Disponibilidad/GetPDF/',
}
