export class Detalle {
    id: number;
    iD_AREA: number;
    compania: string;
    cliente: number;
    nombre: string;
    serie: string;
    documento: string;
    fechA_GUIA: string;
    nocarta: string;
    f_CARTACROBRO: any;
    fechA_VENCIMIENTO: any;
    remision: string;
    referencia: string;
    observaciones: string;
    recogeR_EN: string;
    totaL_SALDO: number;
    totaL_VENCIDOS: number;
    v1A15: number;
    v16A30: number;
    v31A45: number;
    v46A60: number;
    v61A90: number;
    v91A120: number;
    v120: number;
    poR_VENCER2: number;
    poR_VENCER: number;
    p1A7: number;
    p8A15: number;
    p16A30: number;
    p31: number;
    saldO_SIN_CCOBRO: number;
    totaL_INTEGRADO: number;
    diaS_DE_CREDITO: number;
    diaS_SIN_CARTA_C: number;
    fechaCierre: string;
    diasVencimiento: number;

}